version: "3.8"
services:
  myfridge-app:
    build: ./infra/php
    volumes:
      - ./src:/src
  myfridge-web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/src
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /src

  myfridge-db:
    build: ./infra/db
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
