version: '3.9'
services:
  db:
    container_name: db
    image: 'mysql:8.2.0'
    volumes:
      - myfridge_db_data:/var/lib/mysql
      - type: bind
        source: ./db/initdb.d
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./db/conf.d
        target: /etc/mysql/conf.d
    env_file:
      - ./env/db.env
    ports:
      - 3306:3306
  api:
    container_name: api
    build: .
    volumes:
      - type: bind 
        source: ./app
        target: /app
    ports:
      - 5050:5050
    env_file:
      - ./env/api.env
    depends_on:
      - db
volumes:
  myfridge_db_data: